### ISSUE TITLE
Implement defragmentation of `MemoryMappedList`

### ISSUE THREAD

**Issue by hangy** [nickna/Neighborly#51]
#### **Description:**

For performance reasons, vectors are only marked as removed with a tombstone Guid when they are removed with [`MemoryMappedList.Remove(vector)`](https://github.com/nickna/Neighborly/blob/c45759f450697ca7a7e81d6a0ff9f9d80530d8e6/Neighborly/MemoryMappedList.cs#L203). The aim is to implement a method that removes all tombstoned Guids from the [index](https://github.com/nickna/Neighborly/blob/c45759f450697ca7a7e81d6a0ff9f9d80530d8e6/Neighborly/MemoryMappedList.cs#L14) as well as the associated [data](https://github.com/nickna/Neighborly/blob/c45759f450697ca7a7e81d6a0ff9f9d80530d8e6/Neighborly/MemoryMappedList.cs#L15). The method should reorganize the index file and the data file, so that there are no empty blocks between actual records.

#### **Tasks:**

- Research and implement a method that removes old vectors.
- Write unit tests to ensure the correctness and performance of the defragmentation process.

#### **Resources:**

- [`MemoryMappedList.Defrag()`](https://github.com/nickna/Neighborly/blob/c45759f450697ca7a7e81d6a0ff9f9d80530d8e6/Neighborly/MemoryMappedList.cs#L259)

#### **Impact:**

The memory mapped file will not grow indefinitely any more, as vectors are removed or updated.

#### **How to Contribute:**

1. Fork the repository and create a new branch for your changes.
2. Implement the defrag method
3. Ensure all new and existing tests pass.
4. Submit a pull request with a detailed description of the changes.

**Comment by nickna** [comment]
Merged branch into master --> [feat: Defrag() and DefragBatch(), along with tests.](https://github.com/nickna/Neighborly/commit/c6ae5e07e02f96d0f2b0da4ec139d284aedbec63)

Defrag() does a whole-file defragmentation. 
DefragBatch() performs defragmentation in batches of 100 vectors.

Empty space is not reclaimed because I didn't want to shrink the file when deletions occur. I may need to revisit this after testing on different OSes.
